<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PrestashopFacebook\API\FacebookCategoryClient' shared service.

return $this->services['PrestaShop\\Module\\PrestashopFacebook\\API\\FacebookCategoryClient'] = new \PrestaShop\Module\PrestashopFacebook\API\FacebookCategoryClient(${($_ = isset($this->services['PrestaShop\\Module\\PrestashopFacebook\\Factory\\GoogleCategoryEssentialsApiClientFactory']) ? $this->services['PrestaShop\\Module\\PrestashopFacebook\\Factory\\GoogleCategoryEssentialsApiClientFactory'] : ($this->services['PrestaShop\\Module\\PrestashopFacebook\\Factory\\GoogleCategoryEssentialsApiClientFactory'] = new \PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory())) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PrestashopFacebook\\Repository\\GoogleCategoryRepository']) ? $this->services['PrestaShop\\Module\\PrestashopFacebook\\Repository\\GoogleCategoryRepository'] : $this->load('getGoogleCategoryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PrestashopFacebook\\Handler\\ErrorHandler\\ErrorHandler']) ? $this->services['PrestaShop\\Module\\PrestashopFacebook\\Handler\\ErrorHandler\\ErrorHandler'] : $this->load('getErrorHandlerService.php')) && false ?: '_'});
