<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\Ps_facebook\Translations\PsFacebookTranslations' shared service.

return $this->services['PrestaShop\\Module\\Ps_facebook\\Translations\\PsFacebookTranslations'] = new \PrestaShop\Module\Ps_facebook\Translations\PsFacebookTranslations(${($_ = isset($this->services['ps_facebook']) ? $this->services['ps_facebook'] : $this->load('getPsFacebookService.php')) && false ?: '_'});
