services:
  PrestaShop\Module\PrestashopFacebook\API\FacebookCategoryClient:
    class: PrestaShop\Module\PrestashopFacebook\API\FacebookCategoryClient
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory'
      - '@PrestaShop\Module\PrestashopFacebook\Repository\GoogleCategoryRepository'
      - '@PrestaShop\Module\PrestashopFacebook\Handler\ErrorHandler\ErrorHandler'

  PrestaShop\Module\PrestashopFacebook\API\FacebookClient:
    class: PrestaShop\Module\PrestashopFacebook\API\FacebookClient
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory'
      - '@PrestaShop\Module\PrestashopFacebook\Provider\AccessTokenProvider'
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PrestashopFacebook\Handler\ErrorHandler\ErrorHandler'
      - '@PrestaShop\Module\PrestashopFacebook\Handler\ConfigurationHandler'

  PrestaShop\Module\PrestashopFacebook\API\EventSubscriber\AccountSuspendedSubscriber:
    class: PrestaShop\Module\PrestashopFacebook\API\EventSubscriber\AccountSuspendedSubscriber
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
