<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcuiqcv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcuiqcv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGcuiqcv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGcuiqcv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGcuiqcv\appProdProjectContainer([
    'container.build_hash' => 'Gcuiqcv',
    'container.build_id' => '94ade8a3',
    'container.build_time' => 1634993885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcuiqcv');
