<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFj9xpxb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFj9xpxb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFj9xpxb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFj9xpxb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFj9xpxb\appProdProjectContainer([
    'container.build_hash' => 'Fj9xpxb',
    'container.build_id' => '9c1fad5e',
    'container.build_time' => 1634751058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFj9xpxb');
