<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGjxz9nq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGjxz9nq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGjxz9nq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGjxz9nq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGjxz9nq\appDevDebugProjectContainer([
    'container.build_hash' => 'Gjxz9nq',
    'container.build_id' => '33526ccc',
    'container.build_time' => 1635677695,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGjxz9nq');
